spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
          - StripPrefix=2
          - name: Ejemplo
            args:
              mensaje: Hola mi mensaje personalizado
              cookieNombre: usuario
              cookieValor: DanielRuiz
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 654321
          - AddRequestParameter=nombre, Daniel  
          - SetResponseHeader=Content-Type, text/plain    